// Word-Arrays for 24h Wordclock, see http://www.mikrocontroller.net/articles/WordClock24h
// Von-Neumann-Variant, Data from WC24h_18x16_V2_2010_2003_15_Dez_2014 CodeGen v0.09
// Code-Generator see https://gist.github.com/TorstenC/aec0724be4afcd1d7545
// tbl_modes[MODES_COUNT]: 777 bytes
// tbl_hours[HOUR_MODES_COUNT][HOUR_COUNT][MAX_HOUR_WORDS]: 1200 bytes
// tbl_minutes[MINUTE_MODES_COUNT][MINUTE_COUNT]: 4800 bytes
// illumination[1][WP_COUNT]: 237 bytes
// total (tbl_minutes + tbl_hours + tbl_modes + illumination): 7014 bytes

#define ModesCount 17 // deprecated
#define MODES_COUNT 17 // count of different display modes
// #define MaxHourWordsPlusOne 7 // deprecated
#define MAX_HOUR_WORDS 6 // how many words for hour display (no end token)
#define HourCount 25 // deprecated
#define HOUR_COUNT 25 // 24 plus one to distinguish between before and after full hour
// #define MaxMinuteWordsPlusOne 8 // deprecated
#define MAX_MINUTE_WORDS 7 // how many words for minute display (no end token)
#define MinuteCount 60 // deprecated
#define MINUTE_COUNT 60
#define HourModesCount 8 // deprecated
#define MinuteModesCount 10 // deprecated

struct Modes {
uint8_t minute_txt; // we don´t need minute_txt_last
uint8_t hour_txt;
const char* description;
};
struct MinuteDisplay {
uint8_t hourOffset; // offset for hour display
uint8_t wordIdx[MAX_MINUTE_WORDS];
};
enum HourMode {
HM_1, // 0 = Mode 1: "HH (12) (ZWÖLF)"
HM_2, // 1 = Mode 2: "HH (12) - (MITTERNACHT, ZWÖLF)"
HM_3, // 2 = Mode 3: "HH UHR (12) (NULL UHR, ZWÖLF UHR)"
HM_4, // 3 = Mode 4: "HH UHR (12) NACHTS"
HM_5, // 4 = Mode 5: "HH UHR (24)"
HM_6, // 5 = Mode 6: "ES IST HH UHR (12)"
HM_7, // 6 = Mode 7: "ES IST HH UHR (24)"
HM_24, // 7 = Mode 24: "MITTERNACHT"
HOUR_MODES_COUNT // Number of HourModes
};

enum MinuteMode {
MM_1, // 0 = Mode 1: "ES IST MM NACH"
MM_2, // 1 = Mode 2: "ES IST MM MINUTEN NACH"
MM_3, // 2 = Mode 3: "ES IST MM MINUTEN NACH (VIERTEL NACH, HALB, VIERTEL VOR) - OSSI"
MM_4, // 3 = Mode 4: "ES IST MM MINUTEN NACH (VIERTEL NACH, HALB, DREIVIERTEL) - OESI"
MM_5, // 4 = Mode 5: "ES IST MM MINUTEN NACH (VIERTEL, HALB, DREIVIERTEL) - RHEIN/ RUHR"
MM_6, // 5 = Mode 6: "ES IST MM MINUTEN NACH (VIERTEL NACH, HALB, DREIVIERTEL) - SCHWABEN"
MM_10, // 6 = Mode 10: "MM"
MM_11, // 7 = Mode 11: "UND MM MINUTEN"
MM_12, // 8 = Mode 12: "ES IST MM MINUTEN VOR"
MM_7, // 9 = Mode 7: "ES IST MM MINUTEN NACH (VIERTEL, HALB,DREIVIERTEL) - WESSI"
MINUTE_MODES_COUNT // Number of MinuteModes
};
#ifdef TABLES_EXTERN
extern const struct Modes           tbl_modes[MODES_COUNT];
extern const uint8_t                tbl_hours[HOUR_MODES_COUNT][HOUR_COUNT][MAX_HOUR_WORDS];
extern const struct MinuteDisplay   tbl_minutes[MINUTE_MODES_COUNT][MINUTE_COUNT];
#else
const struct Modes tbl_modes[MODES_COUNT] = {
{ MM_10, HM_6, "ES IST HH UHR MM (12)" },
{ MM_10, HM_7, "ES IST HH UHR MM (24)" },
{ MM_11, HM_6, "ES IST HH UHR UND MM MINUTEN (12)" },
{ MM_11, HM_7, "ES IST HH UHR UND MM MINUTEN (24)" },
{ MM_2, HM_4, "ES IST MM MINUTEN NACH HH UHR (12) NACHTS" },
{ MM_2, HM_5, "ES IST MM MINUTEN NACH HH UHR (24)" },
{ MM_3, HM_2, "OSSI - ES IST MM MINUTEN NACH HH (12)" },
{ MM_3, HM_4, "OSSI - ES IST MM MINUTEN NACH HH UHR (12) NACHTS" },
{ MM_4, HM_2, "OESI- ES IST MM MINUTEN NACH HH UHR (12)" },
{ MM_4, HM_4, "OESI - ES IST MM MINUTEN NACH HH UHR (12) NACHTS" },
{ MM_5, HM_2, "RHEIN/ RUHR - ES IST MM MINUTEN NACH HH (12)" },
{ MM_5, HM_4, "RHEIN/ RUHR - ES IST MM MINUTEN NACH HH UHR (12) NACHTS" },
{ MM_6, HM_4, "SCHWABEN - ES IST MM MINUTEN NACH HH (12)" },
{ MM_6, HM_2, "SCHWABEN - ES IST MM MINUTEN NACH HH UHR (12) NACHTS" },
{ MM_7, HM_4, "WESSI - ES IST MM MINUTEN NACH HH (12)" },
{ MM_7, HM_2, "WESSI - ES IST MM MINUTEN NACH HH UHR (12) NACHTS" },
{ MM_12, HM_2, "COUNTDOUWN MM MINUTEN VOR MITTERNACHT" }
};

const uint8_t tbl_hours[HOUR_MODES_COUNT][HOUR_COUNT][MAX_HOUR_WORDS]= {
{ // tbl_hours[0][] = Mode 1 HH (12) (ZWÖLF)
{WP_ZWOELF_2}, // 0. Stunde in Mode HM_1 = 0
{WP_EINS_2}, // 1. Stunde in Mode HM_1 = 0
{WP_ZWEI_2}, // 2. Stunde in Mode HM_1 = 0
{WP_DREI_2}, // 3. Stunde in Mode HM_1 = 0
{WP_VIER_2}, // 4. Stunde in Mode HM_1 = 0
{WP_FUENF_2}, // 5. Stunde in Mode HM_1 = 0
{WP_SECHS_2}, // 6. Stunde in Mode HM_1 = 0
{WP_SIEBEN_2}, // 7. Stunde in Mode HM_1 = 0
{WP_ACHT_2}, // 8. Stunde in Mode HM_1 = 0
{WP_NEUN_2}, // 9. Stunde in Mode HM_1 = 0
{WP_ZEHN_2}, // 10. Stunde in Mode HM_1 = 0
{WP_ELF_2}, // 11. Stunde in Mode HM_1 = 0
{WP_ZWOELF_2}, // 12. Stunde in Mode HM_1 = 0
{WP_EINS_2}, // 13. Stunde in Mode HM_1 = 0
{WP_ZWEI_2}, // 14. Stunde in Mode HM_1 = 0
{WP_DREI_2}, // 15. Stunde in Mode HM_1 = 0
{WP_VIER_2}, // 16. Stunde in Mode HM_1 = 0
{WP_FUENF_2}, // 17. Stunde in Mode HM_1 = 0
{WP_SECHS_2}, // 18. Stunde in Mode HM_1 = 0
{WP_SIEBEN_2}, // 19. Stunde in Mode HM_1 = 0
{WP_ACHT_2}, // 20. Stunde in Mode HM_1 = 0
{WP_NEUN_2}, // 21. Stunde in Mode HM_1 = 0
{WP_ZEHN_2}, // 22. Stunde in Mode HM_1 = 0
{WP_ELF_2}, // 23. Stunde in Mode HM_1 = 0
{WP_ZWOELF_2} // 24. Stunde in Mode HM_1 = 0
},
{ // tbl_hours[1][] = Mode 2 HH (12) - (MITTERNACHT, ZWÖLF)
{WP_ZWOELF_2}, // 0. Stunde in Mode HM_2 = 1
{WP_EINS_2}, // 1. Stunde in Mode HM_2 = 1
{WP_ZWEI_2}, // 2. Stunde in Mode HM_2 = 1
{WP_DREI_2}, // 3. Stunde in Mode HM_2 = 1
{WP_VIER_2}, // 4. Stunde in Mode HM_2 = 1
{WP_FUENF_2}, // 5. Stunde in Mode HM_2 = 1
{WP_SECHS_2}, // 6. Stunde in Mode HM_2 = 1
{WP_SIEBEN_2}, // 7. Stunde in Mode HM_2 = 1
{WP_ACHT_2}, // 8. Stunde in Mode HM_2 = 1
{WP_NEUN_2}, // 9. Stunde in Mode HM_2 = 1
{WP_ZEHN_2}, // 10. Stunde in Mode HM_2 = 1
{WP_ELF_2}, // 11. Stunde in Mode HM_2 = 1
{WP_ZWOELF_2}, // 12. Stunde in Mode HM_2 = 1
{WP_EINS_2}, // 13. Stunde in Mode HM_2 = 1
{WP_ZWEI_2}, // 14. Stunde in Mode HM_2 = 1
{WP_DREI_2}, // 15. Stunde in Mode HM_2 = 1
{WP_VIER_2}, // 16. Stunde in Mode HM_2 = 1
{WP_FUENF_2}, // 17. Stunde in Mode HM_2 = 1
{WP_SECHS_2}, // 18. Stunde in Mode HM_2 = 1
{WP_SIEBEN_2}, // 19. Stunde in Mode HM_2 = 1
{WP_ACHT_2}, // 20. Stunde in Mode HM_2 = 1
{WP_NEUN_2}, // 21. Stunde in Mode HM_2 = 1
{WP_ZEHN_2}, // 22. Stunde in Mode HM_2 = 1
{WP_ELF_2}, // 23. Stunde in Mode HM_2 = 1
{WP_ZWOELF_2} // 24. Stunde in Mode HM_2 = 1
},
{ // tbl_hours[2][] = Mode 3 HH UHR (12) (NULL UHR, ZWÖLF UHR)
{WP_ZWOELF_2, WP_UHR_2}, // 0. Stunde in Mode HM_3 = 2
{WP_EIN_3, WP_UHR_2}, // 1. Stunde in Mode HM_3 = 2
{WP_ZWEI_2, WP_UHR_2}, // 2. Stunde in Mode HM_3 = 2
{WP_DREI_2, WP_UHR_2}, // 3. Stunde in Mode HM_3 = 2
{WP_VIER_2, WP_UHR_2}, // 4. Stunde in Mode HM_3 = 2
{WP_FUENF_2, WP_UHR_2}, // 5. Stunde in Mode HM_3 = 2
{WP_SECHS_2, WP_UHR_2}, // 6. Stunde in Mode HM_3 = 2
{WP_SIEBEN_2, WP_UHR_2}, // 7. Stunde in Mode HM_3 = 2
{WP_ACHT_2, WP_UHR_2}, // 8. Stunde in Mode HM_3 = 2
{WP_NEUN_2, WP_UHR_2}, // 9. Stunde in Mode HM_3 = 2
{WP_ZEHN_2, WP_UHR_2}, // 10. Stunde in Mode HM_3 = 2
{WP_ELF_2, WP_UHR_2}, // 11. Stunde in Mode HM_3 = 2
{WP_ZWOELF_2, WP_UHR_2}, // 12. Stunde in Mode HM_3 = 2
{WP_EIN_3, WP_UHR_2}, // 13. Stunde in Mode HM_3 = 2
{WP_ZWEI_2, WP_UHR_2}, // 14. Stunde in Mode HM_3 = 2
{WP_DREI_2, WP_UHR_2}, // 15. Stunde in Mode HM_3 = 2
{WP_VIER_2, WP_UHR_2}, // 16. Stunde in Mode HM_3 = 2
{WP_FUENF_2, WP_UHR_2}, // 17. Stunde in Mode HM_3 = 2
{WP_SECHS_2, WP_UHR_2}, // 18. Stunde in Mode HM_3 = 2
{WP_SIEBEN_2, WP_UHR_2}, // 19. Stunde in Mode HM_3 = 2
{WP_ACHT_2, WP_UHR_2}, // 20. Stunde in Mode HM_3 = 2
{WP_NEUN_2, WP_UHR_2}, // 21. Stunde in Mode HM_3 = 2
{WP_ZEHN_2, WP_UHR_2}, // 22. Stunde in Mode HM_3 = 2
{WP_ELF_2, WP_UHR_2}, // 23. Stunde in Mode HM_3 = 2
{WP_ZWOELF_2, WP_UHR_2} // 24. Stunde in Mode HM_3 = 2
},
{ // tbl_hours[3][] = Mode 4 HH UHR (12) NACHTS
{WP_ZWOELF_2, WP_UHR_2, WP_NACHTS}, // 0. Stunde in Mode HM_4 = 3
{WP_EIN_3, WP_UHR_2, WP_NACHTS}, // 1. Stunde in Mode HM_4 = 3
{WP_ZWEI_2, WP_UHR_2, WP_NACHTS}, // 2. Stunde in Mode HM_4 = 3
{WP_DREI_2, WP_UHR_2, WP_NACHTS}, // 3. Stunde in Mode HM_4 = 3
{WP_VIER_2, WP_UHR_2, WP_FRUEH, WP_MORGENS}, // 4. Stunde in Mode HM_4 = 3
{WP_FUENF_2, WP_UHR_2, WP_FRUEH, WP_MORGENS}, // 5. Stunde in Mode HM_4 = 3
{WP_SECHS_2, WP_UHR_2, WP_MORGENS}, // 6. Stunde in Mode HM_4 = 3
{WP_SIEBEN_2, WP_UHR_2, WP_MORGENS}, // 7. Stunde in Mode HM_4 = 3
{WP_ACHT_2, WP_UHR_2, WP_MORGENS}, // 8. Stunde in Mode HM_4 = 3
{WP_NEUN_2, WP_UHR_2, WP_MORGENS}, // 9. Stunde in Mode HM_4 = 3
{WP_ZEHN_2, WP_UHR_2, WP_VOR_2, WP_MITTAG_S}, // 10. Stunde in Mode HM_4 = 3
{WP_ELF_2, WP_UHR_2, WP_VOR_2, WP_MITTAG_S}, // 11. Stunde in Mode HM_4 = 3
{WP_ZWOELF_2, WP_UHR_2, WP_MITTAG_S}, // 12. Stunde in Mode HM_4 = 3
{WP_EIN_3, WP_UHR_2, WP_MITTAG_S}, // 13. Stunde in Mode HM_4 = 3
{WP_ZWEI_2, WP_UHR_2, WP_MITTAG_S}, // 14. Stunde in Mode HM_4 = 3
{WP_DREI_2, WP_UHR_2, WP_NACH_2, WP_MITTAG_S}, // 15. Stunde in Mode HM_4 = 3
{WP_VIER_2, WP_UHR_2, WP_NACH_2, WP_MITTAG_S}, // 16. Stunde in Mode HM_4 = 3
{WP_FUENF_2, WP_UHR_2, WP_NACH_2, WP_MITTAG_S}, // 17. Stunde in Mode HM_4 = 3
{WP_SECHS_2, WP_UHR_2, WP_ABENDS}, // 18. Stunde in Mode HM_4 = 3
{WP_SIEBEN_2, WP_UHR_2, WP_ABENDS}, // 19. Stunde in Mode HM_4 = 3
{WP_ACHT_2, WP_UHR_2, WP_ABENDS}, // 20. Stunde in Mode HM_4 = 3
{WP_NEUN_2, WP_UHR_2, WP_ABENDS}, // 21. Stunde in Mode HM_4 = 3
{WP_ZEHN_2, WP_UHR_2, WP_ABENDS}, // 22. Stunde in Mode HM_4 = 3
{WP_ELF_2, WP_UHR_2, WP_NACHTS}, // 23. Stunde in Mode HM_4 = 3
{WP_ZWOELF_2, WP_UHR_2, WP_NACHTS} // 24. Stunde in Mode HM_4 = 3
},
{ // tbl_hours[4][] = Mode 5 HH UHR (24)
{WP_NULL_2, WP_UHR_2}, // 0. Stunde in Mode HM_5 = 4
{WP_EIN_3, WP_UHR_2}, // 1. Stunde in Mode HM_5 = 4
{WP_ZWEI_2, WP_UHR_2}, // 2. Stunde in Mode HM_5 = 4
{WP_DREI_2, WP_UHR_2}, // 3. Stunde in Mode HM_5 = 4
{WP_VIER_2, WP_UHR_2}, // 4. Stunde in Mode HM_5 = 4
{WP_FUENF_2, WP_UHR_2}, // 5. Stunde in Mode HM_5 = 4
{WP_SECHS_2, WP_UHR_2}, // 6. Stunde in Mode HM_5 = 4
{WP_SIEBEN_2, WP_UHR_2}, // 7. Stunde in Mode HM_5 = 4
{WP_ACHT_2, WP_UHR_2}, // 8. Stunde in Mode HM_5 = 4
{WP_NEUN_2, WP_UHR_2}, // 9. Stunde in Mode HM_5 = 4
{WP_ZEHN_2, WP_UHR_2}, // 10. Stunde in Mode HM_5 = 4
{WP_ELF_2, WP_UHR_2}, // 11. Stunde in Mode HM_5 = 4
{WP_ZWOELF_2, WP_UHR_2}, // 12. Stunde in Mode HM_5 = 4
{WP_DREI_2, WP_ZEHN_2, WP_UHR_2}, // 13. Stunde in Mode HM_5 = 4
{WP_VIER_2, WP_ZEHN_2, WP_UHR_2}, // 14. Stunde in Mode HM_5 = 4
{WP_FUENF_2, WP_ZEHN_2, WP_UHR_2}, // 15. Stunde in Mode HM_5 = 4
{WP_SECH_2, WP_ZEHN_2, WP_UHR_2}, // 16. Stunde in Mode HM_5 = 4
{WP_SIEB_2, WP_ZEHN_2, WP_UHR_2}, // 17. Stunde in Mode HM_5 = 4
{WP_ACHT_2, WP_ZEHN_2, WP_UHR_2}, // 18. Stunde in Mode HM_5 = 4
{WP_NEUN_2, WP_ZEHN_2, WP_UHR_2}, // 19. Stunde in Mode HM_5 = 4
{WP_ZWANZIG_2, WP_UHR_2}, // 20. Stunde in Mode HM_5 = 4
{WP_EIN_3, WP_UND_3, WP_ZWANZIG_2, WP_UHR_2}, // 21. Stunde in Mode HM_5 = 4
{WP_ZWEI_2, WP_UND_3, WP_ZWANZIG_2, WP_UHR_2}, // 22. Stunde in Mode HM_5 = 4
{WP_DREI_2, WP_UND_3, WP_ZWANZIG_2, WP_UHR_2}, // 23. Stunde in Mode HM_5 = 4
{WP_VIER_2, WP_UND_3, WP_ZWANZIG_2, WP_UHR_2} // 24. Stunde in Mode HM_5 = 4
},
{ // tbl_hours[5][] = Mode 6 ES IST HH UHR (12)
{WP_ES, WP_IST, WP_ZWOELF_1, WP_UHR_1}, // 0. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_EIN_1, WP_UHR_1}, // 1. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ZWEI_1, WP_UHR_1}, // 2. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_DREI_1, WP_UHR_1}, // 3. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_VIER_1, WP_UHR_1}, // 4. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_FUENF_1, WP_UHR_1}, // 5. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_SECHS_1, WP_UHR_1}, // 6. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_SIEBEN_1, WP_UHR_1}, // 7. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ACHT_1, WP_UHR_1}, // 8. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_NEUN_1, WP_UHR_1}, // 9. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ZEHN_1, WP_UHR_1}, // 10. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ELF_1, WP_UHR_1}, // 11. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ZWOELF_1, WP_UHR_1}, // 12. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_EIN_1, WP_UHR_1}, // 13. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ZWEI_1, WP_UHR_1}, // 14. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_DREI_1, WP_UHR_1}, // 15. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_VIER_1, WP_UHR_1}, // 16. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_FUENF_1, WP_UHR_1}, // 17. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_SECHS_1, WP_UHR_1}, // 18. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_SIEBEN_1, WP_UHR_1}, // 19. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ACHT_1, WP_UHR_1}, // 20. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_NEUN_1, WP_UHR_1}, // 21. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ZEHN_1, WP_UHR_1}, // 22. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ELF_1, WP_UHR_1}, // 23. Stunde in Mode HM_6 = 5
{WP_ES, WP_IST, WP_ZWOELF_1, WP_UHR_1} // 24. Stunde in Mode HM_6 = 5
},
{ // tbl_hours[6][] = Mode 7 ES IST HH UHR (24)
{WP_ES, WP_IST, WP_NULL_1, WP_UHR_1}, // 0. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_EIN_1, WP_UHR_1}, // 1. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ZWEI_1, WP_UHR_1}, // 2. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_DREI_1, WP_UHR_1}, // 3. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_VIER_1, WP_UHR_1}, // 4. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_FUENF_1, WP_UHR_1}, // 5. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_SECHS_1, WP_UHR_1}, // 6. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_SIEBEN_1, WP_UHR_1}, // 7. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ACHT_1, WP_UHR_1}, // 8. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_NEUN_1, WP_UHR_1}, // 9. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ZEHN_1, WP_UHR_1}, // 10. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ELF_1, WP_UHR_1}, // 11. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ZWOELF_1, WP_UHR_1}, // 12. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_UHR_1}, // 13. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_UHR_1}, // 14. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_FUENF_1, WP_ZEHN_1, WP_UHR_1}, // 15. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_UHR_1}, // 16. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_UHR_1}, // 17. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_UHR_1}, // 18. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_UHR_1}, // 19. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ZWANZIG_1, WP_UHR_1}, // 20. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_ZWANZIG_1, WP_UHR_1}, // 21. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_ZWANZIG_1, WP_UHR_1}, // 22. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_ZWANZIG_1, WP_UHR_1}, // 23. Stunde in Mode HM_7 = 6
{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_ZWANZIG_1, WP_UHR_1} // 24. Stunde in Mode HM_7 = 6
},
{ // tbl_hours[7][] = Mode 24 MITTERNACHT
{WP_MITTERNACHT}, // 0. Stunde in Mode HM_24 = 7
{}, // 1. Stunde in Mode HM_24 = 7
{}, // 2. Stunde in Mode HM_24 = 7
{}, // 3. Stunde in Mode HM_24 = 7
{}, // 4. Stunde in Mode HM_24 = 7
{}, // 5. Stunde in Mode HM_24 = 7
{}, // 6. Stunde in Mode HM_24 = 7
{}, // 7. Stunde in Mode HM_24 = 7
{}, // 8. Stunde in Mode HM_24 = 7
{}, // 9. Stunde in Mode HM_24 = 7
{}, // 10. Stunde in Mode HM_24 = 7
{}, // 11. Stunde in Mode HM_24 = 7
{}, // 12. Stunde in Mode HM_24 = 7
{}, // 13. Stunde in Mode HM_24 = 7
{}, // 14. Stunde in Mode HM_24 = 7
{}, // 15. Stunde in Mode HM_24 = 7
{}, // 16. Stunde in Mode HM_24 = 7
{}, // 17. Stunde in Mode HM_24 = 7
{}, // 18. Stunde in Mode HM_24 = 7
{}, // 19. Stunde in Mode HM_24 = 7
{}, // 20. Stunde in Mode HM_24 = 7
{}, // 21. Stunde in Mode HM_24 = 7
{}, // 22. Stunde in Mode HM_24 = 7
{}, // 23. Stunde in Mode HM_24 = 7
{WP_MITTERNACHT} // 24. Stunde in Mode HM_24 = 7
}
};

const struct MinuteDisplay tbl_minutes[MINUTE_MODES_COUNT][MINUTE_COUNT]= {
{ // tbl_minutes[0][] = Mode 1 ES IST MM NACH
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_EINS_1, WP_NACH_1}}, // 1. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_NACH_1}}, // 2. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREI_1, WP_NACH_1}}, // 3. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIER_1, WP_NACH_1}}, // 4. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_NACH_1}}, // 5. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_NACH_1}}, // 6. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_NACH_1}}, // 8. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_NACH_1}}, // 9. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_NACH_1}}, // 10. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ELF_1, WP_NACH_1}}, // 11. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_NACH_1}}, // 12. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_NACH_1}}, // 13. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_NACH_1}}, // 14. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_ZEHN_1, WP_NACH_1}}, // 15. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_NACH_1}}, // 16. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_NACH_1}}, // 17. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_NACH_1}}, // 18. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_NACH_1}}, // 19. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_NACH_1}}, // 20. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 21. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 22. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 23. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 24. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 25. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 26. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 27. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 28. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_ZWANZIG_1, WP_NACH_1}}, // 29. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREISSIG_1, WP_NACH_1}}, // 30. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 31. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 32. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 33. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 34. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 35. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 36. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 37. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 38. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_DREISSIG_1, WP_NACH_1}}, // 39. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIERZIG_1, WP_NACH_1}}, // 40. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 41. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 42. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 43. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 44. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 45. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 46. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 47. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 48. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_VIERZIG_1, WP_NACH_1}}, // 49. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENFZIG_1, WP_NACH_1}}, // 50. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 51. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 52. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 53. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 54. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 55. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 56. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 57. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}}, // 58. Minute in Mode MM_1 = 0
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_FUENFZIG_1, WP_NACH_1}} // 59. Minute in Mode MM_1 = 0
},
{ // tbl_minutes[1][] = Mode 2 ES IST MM MINUTEN NACH
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1}}, // 1. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1}}, // 2. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1}}, // 3. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1}}, // 4. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1}}, // 5. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1}}, // 6. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1}}, // 8. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 9. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 10. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 11. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 12. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 13. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 14. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 15. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 16. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 17. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 18. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 19. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 20. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 21. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 22. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 23. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 24. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 25. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 26. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 27. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 28. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 29. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 30. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 31. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 32. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 33. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 34. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 35. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 36. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 37. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 38. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 39. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 40. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 41. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 42. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 43. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 44. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 45. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 46. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 47. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 48. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 49. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 50. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 51. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 52. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 53. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 54. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 55. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 56. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 57. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 58. Minute in Mode MM_2 = 1
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_NACH_1}} // 59. Minute in Mode MM_2 = 1
},
{ // tbl_minutes[2][] = Mode 3 ES IST MM MINUTEN NACH (VIERTEL NACH, HALB, VIERTEL VOR) - OSSI
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1}}, // 1. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1}}, // 2. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1}}, // 3. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1}}, // 4. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1}}, // 5. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1}}, // 6. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1}}, // 8. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 9. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 10. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 11. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 12. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 13. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 14. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIERTEL_2}}, // 15. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 16. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 17. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 18. Minute in Mode MM_3 = 2
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 19. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 20. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 21. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 22. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 23. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 24. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 25. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 26. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 27. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 28. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1, WP_HALB}}, // 29. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_HALB}}, // 30. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1, WP_HALB}}, // 31. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 32. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 33. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 34. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 35. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 36. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 37. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 38. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 39. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZEHN_2, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 40. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 41. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 42. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 43. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 44. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIERTEL_1, WP_VOR_1}}, // 45. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 46. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 47. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 48. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 49. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 50. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1}}, // 51. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1}}, // 52. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1}}, // 53. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1}}, // 54. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1}}, // 55. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1}}, // 56. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1}}, // 57. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1}}, // 58. Minute in Mode MM_3 = 2
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1}} // 59. Minute in Mode MM_3 = 2
},
{ // tbl_minutes[3][] = Mode 4 ES IST MM MINUTEN NACH (VIERTEL NACH, HALB, DREIVIERTEL) - OESI
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1}}, // 1. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1}}, // 2. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1}}, // 3. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1}}, // 4. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1}}, // 5. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1}}, // 6. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1}}, // 8. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 9. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 10. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 11. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 12. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 13. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 14. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_VIERTEL_1, WP_NACH_1}}, // 15. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 16. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 17. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 18. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 19. Minute in Mode MM_4 = 3
{0,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 20. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 21. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 22. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 23. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 24. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 25. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 26. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 27. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_HALB, WP_HALB}}, // 28. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1, WP_HALB}}, // 29. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_HALB}}, // 30. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1, WP_HALB}}, // 31. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 32. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 33. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 34. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 35. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 36. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 37. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 38. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 39. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 40. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 41. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 42. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 43. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 44. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_DREIVIERTEL}}, // 45. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 46. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 47. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 48. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 49. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ZEHN_2, WP_MINUTEN_1, WP_VOR_1}}, // 50. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1}}, // 51. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1}}, // 52. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1}}, // 53. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1}}, // 54. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1}}, // 55. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1}}, // 56. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1}}, // 57. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1}}, // 58. Minute in Mode MM_4 = 3
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1}} // 59. Minute in Mode MM_4 = 3
},
{ // tbl_minutes[4][] = Mode 5 ES IST MM MINUTEN NACH (VIERTEL, HALB, DREIVIERTEL) - RHEIN/ RUHR
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1}}, // 1. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1}}, // 2. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1}}, // 3. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1}}, // 4. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1}}, // 5. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1}}, // 6. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1}}, // 8. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 9. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 10. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 11. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 12. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 13. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 14. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_VIERTEL_2}}, // 15. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 16. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 17. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 18. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 19. Minute in Mode MM_5 = 4
{0,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 20. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 21. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 22. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 23. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 24. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 25. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 26. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 27. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 28. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1, WP_HALB}}, // 29. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_HALB}}, // 30. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1, WP_HALB}}, // 31. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 32. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 33. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 34. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 35. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 36. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 37. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 38. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 39. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 40. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 41. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 42. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 43. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 44. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_DREIVIERTEL}}, // 45. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 46. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 47. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 48. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 49. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 50. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1}}, // 51. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1}}, // 52. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1}}, // 53. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1}}, // 54. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1}}, // 55. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1}}, // 56. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1}}, // 57. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1}}, // 58. Minute in Mode MM_5 = 4
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1}} // 59. Minute in Mode MM_5 = 4
},
{ // tbl_minutes[5][] = Mode 6 ES IST MM MINUTEN NACH (VIERTEL NACH, HALB, DREIVIERTEL) - SCHWABEN
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1}}, // 1. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1}}, // 2. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1}}, // 3. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1}}, // 4. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1}}, // 5. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1}}, // 6. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1}}, // 8. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 9. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 10. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 11. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 12. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 13. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 14. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_VIERTEL_1, WP_NACH_1}}, // 15. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 16. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 17. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 18. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 19. Minute in Mode MM_6 = 5
{0,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_NACH_1}}, // 20. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 21. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 22. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 23. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 24. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 25. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 26. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 27. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 28. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1, WP_HALB}}, // 29. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_HALB}}, // 30. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1, WP_HALB}}, // 31. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 32. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 33. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 34. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 35. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 36. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 37. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 38. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 39. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 40. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 41. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 42. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 43. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 44. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_VIERTEL_1, WP_VOR_1}}, // 45. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 46. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 47. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 48. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 49. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 50. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1}}, // 51. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1}}, // 52. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1}}, // 53. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1}}, // 54. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1}}, // 55. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1}}, // 56. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1}}, // 57. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1}}, // 58. Minute in Mode MM_6 = 5
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1}} // 59. Minute in Mode MM_6 = 5
},
{ // tbl_minutes[6][] = Mode 10 MM
{0}, // 0. Minute in Mode MM_10 = 6
{0,{WP_EINS_2}}, // 1. Minute in Mode MM_10 = 6
{0,{WP_ZWEI_2}}, // 2. Minute in Mode MM_10 = 6
{0,{WP_DREI_2}}, // 3. Minute in Mode MM_10 = 6
{0,{WP_VIER_2}}, // 4. Minute in Mode MM_10 = 6
{0,{WP_FUENF_2}}, // 5. Minute in Mode MM_10 = 6
{0,{WP_SECHS_2}}, // 6. Minute in Mode MM_10 = 6
{0,{WP_SIEBEN_2}}, // 7. Minute in Mode MM_10 = 6
{0,{WP_ACHT_2}}, // 8. Minute in Mode MM_10 = 6
{0,{WP_NEUN_2}}, // 9. Minute in Mode MM_10 = 6
{0,{WP_ZEHN_2}}, // 10. Minute in Mode MM_10 = 6
{0,{WP_ELF_2}}, // 11. Minute in Mode MM_10 = 6
{0,{WP_ZWOELF_2}}, // 12. Minute in Mode MM_10 = 6
{0,{WP_DREI_2, WP_ZEHN_2}}, // 13. Minute in Mode MM_10 = 6
{0,{WP_VIER_2, WP_ZEHN_2}}, // 14. Minute in Mode MM_10 = 6
{0,{WP_FUENF_2, WP_ZEHN_2}}, // 15. Minute in Mode MM_10 = 6
{0,{WP_SECH_2, WP_ZEHN_2}}, // 16. Minute in Mode MM_10 = 6
{0,{WP_SIEB_2, WP_ZEHN_2}}, // 17. Minute in Mode MM_10 = 6
{0,{WP_ACHT_2, WP_ZEHN_2}}, // 18. Minute in Mode MM_10 = 6
{0,{WP_NEUN_2, WP_ZEHN_2}}, // 19. Minute in Mode MM_10 = 6
{0,{WP_ZWANZIG_2}}, // 20. Minute in Mode MM_10 = 6
{0,{WP_EIN_3, WP_UND_3, WP_ZWANZIG_2}}, // 21. Minute in Mode MM_10 = 6
{0,{WP_ZWEI_2, WP_UND_3, WP_ZWANZIG_2}}, // 22. Minute in Mode MM_10 = 6
{0,{WP_DREI_2, WP_UND_3, WP_ZWANZIG_2}}, // 23. Minute in Mode MM_10 = 6
{0,{WP_VIER_2, WP_UND_3, WP_ZWANZIG_2}}, // 24. Minute in Mode MM_10 = 6
{0,{WP_FUENF_2, WP_UND_3, WP_ZWANZIG_2}}, // 25. Minute in Mode MM_10 = 6
{0,{WP_SECHS_2, WP_UND_3, WP_ZWANZIG_2}}, // 26. Minute in Mode MM_10 = 6
{0,{WP_SIEBEN_2, WP_UND_3, WP_ZWANZIG_2}}, // 27. Minute in Mode MM_10 = 6
{0,{WP_ACHT_2, WP_UND_3, WP_ZWANZIG_2}}, // 28. Minute in Mode MM_10 = 6
{0,{WP_NEUN_2, WP_UND_3, WP_ZWANZIG_2}}, // 29. Minute in Mode MM_10 = 6
{0,{WP_DREISSIG_2}}, // 30. Minute in Mode MM_10 = 6
{0,{WP_EIN_3, WP_UND_3, WP_DREISSIG_2}}, // 31. Minute in Mode MM_10 = 6
{0,{WP_ZWEI_2, WP_UND_3, WP_DREISSIG_2}}, // 32. Minute in Mode MM_10 = 6
{0,{WP_DREI_2, WP_UND_3, WP_DREISSIG_2}}, // 33. Minute in Mode MM_10 = 6
{0,{WP_VIER_2, WP_UND_3, WP_DREISSIG_2}}, // 34. Minute in Mode MM_10 = 6
{0,{WP_FUENF_2, WP_UND_3, WP_DREISSIG_2}}, // 35. Minute in Mode MM_10 = 6
{0,{WP_SECHS_2, WP_UND_3, WP_DREISSIG_2}}, // 36. Minute in Mode MM_10 = 6
{0,{WP_SIEBEN_2, WP_UND_3, WP_DREISSIG_2}}, // 37. Minute in Mode MM_10 = 6
{0,{WP_ACHT_2, WP_UND_3, WP_DREISSIG_2}}, // 38. Minute in Mode MM_10 = 6
{0,{WP_NEUN_2, WP_UND_3, WP_DREISSIG_2}}, // 39. Minute in Mode MM_10 = 6
{0,{WP_VIERZIG_2}}, // 40. Minute in Mode MM_10 = 6
{0,{WP_EIN_3, WP_UND_3, WP_VIERZIG_2}}, // 41. Minute in Mode MM_10 = 6
{0,{WP_ZWEI_2, WP_UND_3, WP_VIERZIG_2}}, // 42. Minute in Mode MM_10 = 6
{0,{WP_DREI_2, WP_UND_3, WP_VIERZIG_2}}, // 43. Minute in Mode MM_10 = 6
{0,{WP_VIER_2, WP_UND_3, WP_VIERZIG_2}}, // 44. Minute in Mode MM_10 = 6
{0,{WP_FUENF_2, WP_UND_3, WP_VIERZIG_2}}, // 45. Minute in Mode MM_10 = 6
{0,{WP_SECHS_2, WP_UND_3, WP_VIERZIG_2}}, // 46. Minute in Mode MM_10 = 6
{0,{WP_SIEBEN_2, WP_UND_3, WP_VIERZIG_2}}, // 47. Minute in Mode MM_10 = 6
{0,{WP_ACHT_2, WP_UND_3, WP_VIERZIG_2}}, // 48. Minute in Mode MM_10 = 6
{0,{WP_NEUN_2, WP_UND_3, WP_VIERZIG_2}}, // 49. Minute in Mode MM_10 = 6
{0,{WP_FUENFZIG_2}}, // 50. Minute in Mode MM_10 = 6
{0,{WP_EIN_3, WP_UND_3, WP_FUENFZIG_2}}, // 51. Minute in Mode MM_10 = 6
{0,{WP_ZWEI_2, WP_UND_3, WP_FUENFZIG_2}}, // 52. Minute in Mode MM_10 = 6
{0,{WP_DREI_2, WP_UND_3, WP_FUENFZIG_2}}, // 53. Minute in Mode MM_10 = 6
{0,{WP_VIER_2, WP_UND_3, WP_FUENFZIG_2}}, // 54. Minute in Mode MM_10 = 6
{0,{WP_FUENF_2, WP_UND_3, WP_FUENFZIG_2}}, // 55. Minute in Mode MM_10 = 6
{0,{WP_SECHS_2, WP_UND_3, WP_FUENFZIG_2}}, // 56. Minute in Mode MM_10 = 6
{0,{WP_SIEBEN_2, WP_UND_3, WP_FUENFZIG_2}}, // 57. Minute in Mode MM_10 = 6
{0,{WP_ACHT_2, WP_UND_3, WP_FUENFZIG_2}}, // 58. Minute in Mode MM_10 = 6
{0,{WP_NEUN_2, WP_UND_3, WP_FUENFZIG_2}} // 59. Minute in Mode MM_10 = 6
},
{ // tbl_minutes[7][] = Mode 11 UND MM MINUTEN
{0}, // 0. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_EINE_2, WP_MINUTE_2}}, // 1. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWEI_2, WP_MINUTEN_2}}, // 2. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREI_2, WP_MINUTEN_2}}, // 3. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIER_2, WP_MINUTEN_2}}, // 4. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENF_2, WP_MINUTEN_2}}, // 5. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SECHS_2, WP_MINUTEN_2}}, // 6. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SIEBEN_2, WP_MINUTEN_2}}, // 7. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ACHT_2, WP_MINUTEN_2}}, // 8. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_NEUN_2, WP_MINUTEN_2}}, // 9. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 10. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ELF_2, WP_MINUTEN_2}}, // 11. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWOELF_2, WP_MINUTEN_2}}, // 12. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREI_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 13. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIER_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 14. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENF_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 15. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SECH_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 16. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SIEB_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 17. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ACHT_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 18. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_NEUN_2, WP_ZEHN_2, WP_MINUTEN_2}}, // 19. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWANZIG_2}}, // 20. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_EIN_3, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 21. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWEI_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 22. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREI_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 23. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIER_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 24. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENF_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 25. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SECHS_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 26. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SIEBEN_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 27. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ACHT_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 28. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_NEUN_2, WP_UND_3, WP_ZWANZIG_2, WP_MINUTEN_2}}, // 29. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREISSIG_2, WP_MINUTEN_2}}, // 30. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_EIN_3, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 31. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWEI_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 32. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREI_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 33. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIER_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 34. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENF_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 35. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SECHS_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 36. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SIEBEN_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 37. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ACHT_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 38. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_NEUN_2, WP_UND_3, WP_DREISSIG_2, WP_MINUTEN_2}}, // 39. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIERZIG_2, WP_MINUTEN_2}}, // 40. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_EIN_3, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 41. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWEI_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 42. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREI_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 43. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIER_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 44. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENF_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 45. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SECHS_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 46. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SIEBEN_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 47. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ACHT_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 48. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_NEUN_2, WP_UND_3, WP_VIERZIG_2, WP_MINUTEN_2}}, // 49. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 50. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_EIN_3, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 51. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ZWEI_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 52. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_DREI_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 53. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_VIER_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 54. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_FUENF_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 55. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SECHS_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 56. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_SIEBEN_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 57. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_ACHT_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}}, // 58. Minute in Mode MM_11 = 7
{0,{WP_UND_2, WP_NEUN_2, WP_UND_3, WP_FUENFZIG_2, WP_MINUTEN_2}} // 59. Minute in Mode MM_11 = 7
},
{ // tbl_minutes[8][] = Mode 12 ES IST MM MINUTEN VOR
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 1. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 2. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 3. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 4. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 5. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 6. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 7. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 8. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 9. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENFZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 10. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 11. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 12. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 13. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 14. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 15. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 16. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 17. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 18. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 19. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIERZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 20. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 21. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 22. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 23. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 24. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 25. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 26. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 27. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 28. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 29. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREISSIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 30. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 31. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 32. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 33. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 34. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 35. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIER_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 36. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREI_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 37. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 38. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_EIN_1, WP_UND_1, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 39. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWANZIG_1, WP_MINUTEN_1, WP_VOR_1}}, // 40. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 41. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 42. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 43. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 44. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 45. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 46. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 47. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 48. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 49. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 50. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1}}, // 51. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1}}, // 52. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1}}, // 53. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1}}, // 54. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1}}, // 55. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1}}, // 56. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1}}, // 57. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1}}, // 58. Minute in Mode MM_12 = 8
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1}} // 59. Minute in Mode MM_12 = 8
},
{ // tbl_minutes[9][] = Mode 7 ES IST MM MINUTEN NACH (VIERTEL, HALB,DREIVIERTEL) - WESSI
{0,{WP_ES, WP_IST}}, // 0. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1}}, // 1. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1}}, // 2. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1}}, // 3. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1}}, // 4. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1}}, // 5. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1}}, // 6. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1}}, // 7. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1}}, // 8. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1}}, // 9. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 10. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 11. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1}}, // 12. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 13. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 14. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_VIERTEL_1}}, // 15. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_SECH_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 16. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_SIEB_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 17. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_ACHT_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 18. Minute in Mode MM_7 = 9
{0,{WP_ES, WP_IST, WP_NEUN_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1}}, // 19. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 20. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 21. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 22. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 23. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 24. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 25. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 26. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 27. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1, WP_HALB}}, // 28. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1, WP_HALB}}, // 29. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_HALB}}, // 30. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_NACH_1, WP_HALB}}, // 31. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 32. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 33. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 34. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 35. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 36. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 37. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 38. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 39. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 40. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 41. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 42. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 43. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_NACH_1, WP_HALB}}, // 44. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_DREIVIERTEL}}, // 45. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_VIER_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 46. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_DREI_1, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 47. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZWOELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 48. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ELF_1, WP_MINUTEN_1, WP_VOR_1}}, // 49. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZEHN_1, WP_MINUTEN_1, WP_VOR_1}}, // 50. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_NEUN_1, WP_MINUTEN_1, WP_VOR_1}}, // 51. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ACHT_1, WP_MINUTEN_1, WP_VOR_1}}, // 52. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_SIEBEN_1, WP_MINUTEN_1, WP_VOR_1}}, // 53. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_SECHS_1, WP_MINUTEN_1, WP_VOR_1}}, // 54. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_FUENF_1, WP_MINUTEN_1, WP_VOR_1}}, // 55. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_VIER_1, WP_MINUTEN_1, WP_VOR_1}}, // 56. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_DREI_1, WP_MINUTEN_1, WP_VOR_1}}, // 57. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_ZWEI_1, WP_MINUTEN_1, WP_VOR_1}}, // 58. Minute in Mode MM_7 = 9
{1,{WP_ES, WP_IST, WP_EINE_1, WP_MINUTE_1, WP_VOR_1}} // 59. Minute in Mode MM_7 = 9
},
};
#endif
